//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Triton.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Triton.Resources.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed data query..
        /// </summary>
        internal static string BadQuery {
            get {
                return ResourceManager.GetString("BadQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt has been made to overwrite data already edited by another user..
        /// </summary>
        internal static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data server has returned an error..
        /// </summary>
        internal static string DbFailure {
            get {
                return ResourceManager.GetString("DbFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has not been found..
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the resource has been denied..
        /// </summary>
        internal static string FailureForbidden {
            get {
                return ResourceManager.GetString("FailureForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred during the operation..
        /// </summary>
        internal static string FailureUnknown {
            get {
                return ResourceManager.GetString("FailureUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was performed already..
        /// </summary>
        internal static string Idempotency {
            get {
                return ResourceManager.GetString("Idempotency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service has not been loaded..
        /// </summary>
        internal static string MissingService {
            get {
                return ResourceManager.GetString("MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service has not been loaded..
        /// </summary>
        internal static string MissingXService {
            get {
                return ResourceManager.GetString("MissingXService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model for the specified entities does not match..
        /// </summary>
        internal static string ModelMismatch {
            get {
                return ResourceManager.GetString("ModelMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network error has occurred..
        /// </summary>
        internal static string NetworkFailure {
            get {
                return ResourceManager.GetString("NetworkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has completed successfully..
        /// </summary>
        internal static string OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested query returns too much data. Please, filter the query or reduce its size before executing it..
        /// </summary>
        internal static string QueryOverLimit {
            get {
                return ResourceManager.GetString("QueryOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the service has found an error..
        /// </summary>
        internal static string ServiceFailure {
            get {
                return ResourceManager.GetString("ServiceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A malicious use of the Tritón API has been detected..
        /// </summary>
        internal static string Tamper {
            get {
                return ResourceManager.GetString("Tamper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt has been made to use a service before configuring it..
        /// </summary>
        internal static string UnconfiguredServiceError {
            get {
                return ResourceManager.GetString("UnconfiguredServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfigured value: {0}.
        /// </summary>
        internal static string UnconfiguredValueX {
            get {
                return ResourceManager.GetString("UnconfiguredValueX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error..
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
