using Microsoft.EntityFrameworkCore;
using TheXDS.Triton.EFCore.Services;
using TheXDS.Triton.SecurityEssentials.Ef.Models;
using TheXDS.Triton.Services;

namespace TheXDS.Triton.SecurityEssentials.Ef.Services.Base;

/// <summary>
/// Base class for Triton services that allow access to a data context
/// with authentication and permission information for users.
/// </summary>
/// <typeparam name="T">
/// Type of <see cref="DbContext"/> that contains the
/// <see cref="DbSet{TEntity}"/> needed to implement user authentication
/// and permissions.
/// </typeparam>
public abstract class UserServiceBase<T> : UserServiceBase, IEfUserService<T> where T : DbContext, IUserDbContext, new()
{
    /// <summary>
    /// Initializes a new instance of the
    /// <see cref="UserServiceBase{T}"/> class, automatically detecting the
    /// transaction configuration to use.
    /// </summary>
    /// <param name="factory">Transaction factory to use.</param>
    public UserServiceBase(ITransactionFactory factory) : base(factory)
    {
    }

    /// <summary>
    /// Initializes a new instance of the
    /// <see cref="UserServiceBase{T}"/> class, specifying the configuration
    /// to use.
    /// </summary>
    /// <param name="transactionConfiguration">
    /// Configuration to use for transactions generated by this service.
    /// </param>
    /// <param name="factory">Transaction factory to use.</param>
    protected UserServiceBase(IMiddlewareConfigurator transactionConfiguration, EfCoreTransFactory<T> factory)
        : base(transactionConfiguration, factory)
    {
    }
}
