using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Storage;
using System.Reflection;
using TheXDS.MCART.Exceptions;
using TheXDS.MCART.Types.Base;
using TheXDS.MCART.Types.Extensions;
using TheXDS.Triton.Services;
using St = TheXDS.Triton.EFCore.Resources.Strings.Exceptions;
using static TheXDS.Triton.Services.FailureReason;

namespace TheXDS.Triton.EFCore.Services.Base;

/// <summary>
/// Base class that allows defining data transactions.
/// </summary>
/// <typeparam name="T">
/// Type of data context to use within the transaction.
/// </typeparam>
public abstract class CrudTransactionBase<T> : AsyncDisposable where T : DbContext
{
    /// <summary>
    /// Gets the configuration available for this transaction.
    /// </summary>
    protected readonly IMiddlewareRunner _runner;

    /// <summary>
    /// Gets the active instance of the data context to use for this transaction.
    /// </summary>
    protected readonly T _context;

    /// <summary>
    /// Initializes a new instance of the <see cref="CrudTransactionBase{T}"/> class.
    /// </summary>
    /// <param name="runner">
    /// Configuration to use for the transaction.
    /// </param>
    /// <param name="options">
    /// Options to use when calling the data context constructor.
    /// Set this parameter to <see langword="null"/> to use the
    /// public parameterless constructor.
    /// </param>
    protected CrudTransactionBase(IMiddlewareRunner runner, DbContextOptions? options = null) : this(runner, CreateContext(options))
    {
    }

    /// <summary>
    /// Wraps an operation in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TResult">Type of the operation result.</typeparam>
    /// <param name="action">Crud action to execute.</param>
    /// <param name="op">Operation to execute.</param>
    /// <param name="result">Result of the operation.</param>
    /// <param name="args">Arguments to pass to the operation.</param>
    /// <returns>
    /// The result generated by the operation, or a
    /// <see cref="ServiceResult"/> representing an error in it.
    /// </returns>
    protected ServiceResult? TryCall<TResult>(CrudAction action, Delegate op, out TResult result, params object?[]? args)
    {
        result = default!;
        try
        {
            if (_runner.RunPrologue(action, args?.Cast<ChangeTrackerItem>()) is { } r) return r;
            if (op.Method.ReturnType == typeof(void))
            {
                op.DynamicInvoke(args);
            }
            else if (typeof(TResult).IsAssignableFrom(op.Method.ReturnType))
            {
                result = (TResult)op.DynamicInvoke(args)!;
            }
            else
            {
                throw new InvalidCastException();
            }
            return _runner.RunEpilogue(action, new[] { GetFromResult(action, result) }.NotNull());
        }
        catch (InvalidCastException)
        {
            throw;
        }
        catch (TargetInvocationException tiex)
        {
            return tiex.InnerException is ArgumentException ? (ServiceResult)BadQuery : ResultFromException(tiex.InnerException ?? tiex);
        }
        catch (Exception ex)
        {
            return ResultFromException(ex);
        }
    }

    /// <summary>
    /// Wraps an operation in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TResult">Type of the operation result.</typeparam>
    /// <param name="action">Crud action to execute.</param>
    /// <param name="op">Operation to execute.</param>
    /// <param name="instance">
    /// The instance on which to invoke the method.
    /// </param>
    /// <param name="result">Result of the operation.</param>
    /// <param name="args">Arguments to pass to the operation.</param>
    /// <returns>
    /// The result generated by the operation, or a
    /// <see cref="ServiceResult"/> representing an error in it.
    /// </returns>
    protected ServiceResult? TryCall<TResult>(CrudAction action, MethodInfo op, object instance, out TResult result, params object?[]? args)
    {
        result = default!;
        try
        {
            if (_runner.RunPrologue(action, args?.Cast<ChangeTrackerItem>()) is { } r) return r;
            if (op.ReturnType == typeof(void))
            {
                op.Invoke(instance, args);
            }
            else if (typeof(TResult).IsAssignableFrom(op.ReturnType))
            {
                result = (TResult)op.Invoke(instance, args)!;
            }
            else
            {
                throw new InvalidCastException();
            }
            return _runner.RunEpilogue(action, new[] { GetFromResult(action, result) }.NotNull());
        }
        catch (InvalidCastException)
        {
            throw;
        }
        catch (TargetInvocationException tiex)
        {
            return tiex.InnerException is ArgumentException ? (ServiceResult)BadQuery : ResultFromException(tiex.InnerException ?? tiex);
        }
        catch (Exception ex)
        {
            return ResultFromException(ex);
        }
    }

    /// <summary>
    /// Wraps an operation in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TResult">
    /// Type of the operation result.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Operation to execute.
    /// </param>
    /// <param name="args">
    /// Arguments to pass to the operation.
    /// </param>
    /// <returns>
    /// The result generated by the operation, or a
    /// <see cref="ServiceResult{T}"/> representing an error in it.
    /// </returns>
    protected ServiceResult<TResult?>? TryCall<TResult>(CrudAction action, Delegate op, params object?[]? args)
    {
        if (op.Method.ReturnType == typeof(void))
        {
            throw new InvalidOperationException(string.Format(St.NonVoidMethodExpected, typeof(TResult)));
        }
        var svcResult = TryCall(action, op, out TResult result, args)?.CastUp(result) ?? new ServiceResult<TResult?>(result);
        return svcResult;
    }

    /// <summary>
    /// Wraps an operation in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Operation to execute.
    /// </param>
    /// <param name="args">
    /// Arguments to pass to the operation.
    /// </param>
    /// <returns>
    /// The result generated by the operation, or a
    /// <see cref="ServiceResult"/> representing an error in it.
    /// </returns>
    protected ServiceResult? TryCall(CrudAction action, Delegate op, params object?[]? args)
    {
        return TryCall<object?>(action, op, out _, args);
    }

    /// <summary>
    /// Wraps an operation in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="operation">
    /// Operation to execute.
    /// </param>
    /// <param name="entities">
    /// Arguments to pass to the operation.
    /// </param>
    /// <returns>
    /// The result generated by the operation, or a
    /// <see cref="ServiceResult"/> representing an error in it.
    /// </returns>
    protected ServiceResult TryCall<TModel>(CrudAction action, Action<object[]> operation, TModel[] entities) where TModel : Model
    {
        try
        {
            if (_runner.RunPrologue(action, entities.Select(p => GetFromResult(action, p)).NotNull()) is { } r) return r;
            operation.Invoke([.. entities.Cast<object>()]);
            return _runner.RunEpilogue(action, entities.Select(p => GetFromResult(action, p)).NotNull()) ?? ServiceResult.Ok;
        }
        catch (InvalidCastException)
        {
            throw;
        }
        catch (TargetInvocationException tiex)
        {
            return ResultFromException(tiex.InnerException!);
        }
        catch (Exception ex)
        {
            return ResultFromException(ex);
        }
    }

    /// <summary>
    /// Wraps a task call in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TModel">
    /// Type of the task result.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Task to execute.
    /// </param>
    /// <param name="entity">
    /// Entity that was passed as an argument to the task. If the task
    /// does not receive a <see cref="Model"/> as an argument, this value
    /// should be set to <see langword="null"/>.
    /// </param>
    /// <returns>
    /// The result generated by the task, or a
    /// <see cref="ServiceResult"/> representing an error in the operation.
    /// </returns>
    protected async Task<ServiceResult<TModel?>> TryCallAsync<TModel>(CrudAction action, Task<TModel?> op, TModel? entity) where TModel : Model
    {
        try
        {
            if (_runner.RunPrologue(action, new[] { GetFromResult(action, entity) }.NotNull()) is { } r) return r.CastUp<ServiceResult<TModel?>>();
            var result = await op;
            return _runner.RunEpilogue(action, new[] { GetFromResult(action, result as Model ?? entity) }.NotNull())?.CastUp<ServiceResult<TModel?>>()
                ?? new ServiceResult<TModel?>(result ?? entity);
        }
        catch (InvalidCastException)
        {
            throw;
        }
        catch (TargetInvocationException tiex)
        {
            return ResultFromException(tiex.InnerException!).CastUp<TModel>(default!);
        }
        catch (Exception ex)
        {
            return ResultFromException(ex).CastUp<ServiceResult<TModel?>>();
        }
    }

    /// <summary>
    /// Wraps an async operation call in a safe context that will return a
    /// <see cref="ServiceResult{Model}"/> representing an error if an exception occurs.
    /// </summary>
    /// <param name="action">
    /// The Crud action to execute.
    /// </param>
    /// <param name="op">
    /// The task to execute.
    /// </param>
    /// <param name="entity">
    /// The entity that was passed as an argument to the task. If the task
    /// does not receive a <see cref="Model"/> as an argument, this value
    /// should be set to <see langword="null"/>.
    /// </param>
    /// <returns>
    /// The result generated by the task, or a <see cref="ServiceResult{Model}"/>
    /// representing an error in the operation.
    /// </returns>
    protected async Task<ServiceResult<Model?>> TryCallAsync(CrudAction action, Task<object?> op, Model? entity)
    {
        try
        {
            if (_runner.RunPrologue(action, new[] { GetFromResult(action, entity) }.NotNull()) is { } r) return r.CastUp<ServiceResult<Model?>>();
            var result = await op;
            return _runner.RunEpilogue(action, new[] { GetFromResult(action, result as Model ?? entity) }.NotNull())?.CastUp<ServiceResult<Model?>>()
                ?? new ServiceResult<Model?>(result as Model ?? entity);
        }
        catch (InvalidCastException)
        {
            throw;
        }
        catch (TargetInvocationException tiex)
        {
            return ResultFromException(tiex.InnerException!).CastUp<Model>(default!);
        }
        catch (Exception ex)
        {
            return ResultFromException(ex).CastUp<ServiceResult<Model?>>();
        }
    }

    /// <summary>
    /// Wraps a task call in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TModel">
    /// Type of the task result.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Task to execute.
    /// </param>
    /// <param name="entity">
    /// Entity that was passed as an argument to the task. If the task
    /// does not receive a <see cref="Model"/> as an argument, this value
    /// should be set to <see langword="null"/>.
    /// </param>
    /// <returns>
    /// The result generated by the task, or a
    /// <see cref="ServiceResult"/> representing an error in the operation.
    /// </returns>
    protected async Task<ServiceResult> TryCallAsync<TModel>(CrudAction action, Task op, TModel? entity) where TModel : Model
    {
        try
        {
            if (_runner.RunPrologue(action, new[] { GetFromResult(action, entity) }.NotNull()) is { } r) return r.CastUp<ServiceResult<TModel?>>();
            await op;
            return _runner.RunEpilogue(action, new[] { GetFromResult(action, entity) }.NotNull())?.CastUp<ServiceResult<TModel?>>() ?? new ServiceResult<TModel?>(entity);
        }
        catch (InvalidCastException)
        {
            throw;
        }
        catch (TargetInvocationException tiex)
        {
            return ResultFromException(tiex.InnerException!);
        }
        catch (Exception ex)
        {
            return ResultFromException(ex).CastUp<ServiceResult<TModel?>>();
        }
    }

    /// <summary>
    /// Wraps a task call in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TModel">
    /// Type of the task result.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Task to execute.
    /// </param>
    /// <returns>
    /// The result generated by the task, or a
    /// <see cref="ServiceResult"/> representing an error in the operation.
    /// </returns>
    protected Task<ServiceResult> TryCallAsync<TModel>(CrudAction action, Task op) where TModel : Model
    {
        return TryCallAsync<Model>(action, op, null);
    }

    /// <summary>
    /// Wraps a task call in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TModel">
    /// Type of the task result.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Task to execute.
    /// </param>
    /// <returns>
    /// The result generated by the task, or a
    /// <see cref="ServiceResult"/> representing an error in the operation.
    /// </returns>
    protected Task<ServiceResult<TModel?>> TryCallAsync<TModel>(CrudAction action, Task<TModel?> op) where TModel : Model
    {
        return TryCallAsync(action, op, null);
    }

    /// <summary>
    /// Wraps a task call in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TModel">
    /// Type of the task result.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Task to execute.
    /// </param>
    /// <returns>
    /// The result generated by the task, or a
    /// <see cref="ServiceResult"/> representing an error in the operation.
    /// </returns>
    protected Task<ServiceResult<TModel?>> TryCallAsync<TModel>(CrudAction action, ValueTask<TModel?> op) where TModel : Model
    {
        return TryCallAsync(action, op.AsTask(), null);
    }

    /// <summary>
    /// Wraps a task call in a safe context that will return an error result
    /// when an exception occurs.
    /// </summary>
    /// <typeparam name="TModel">
    /// Type of the task result.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="op">
    /// Task to execute.
    /// </param>
    /// <param name="entity">
    /// Entity that was passed as an argument to the task. If the task
    /// does not receive a <see cref="Model"/> as an argument, this value
    /// should be set to <see langword="null"/>.
    /// </param>
    /// <returns>
    /// The result generated by the task, or a
    /// <see cref="ServiceResult"/> representing an error in the operation.
    /// </returns>
    protected Task<ServiceResult<TModel?>> TryCallAsync<TModel>(CrudAction action, ValueTask<TModel?> op, TModel? entity) where TModel : Model
    {
        return TryCallAsync(action, op.AsTask(), entity);
    }

    /// <summary>
    /// Executes a Crud write operation.
    /// </summary>
    /// <typeparam name="TModel">
    /// Model used by the operation.
    /// </typeparam>
    /// <param name="action">
    /// Crud action to execute.
    /// </param>
    /// <param name="operation">
    /// Operation to execute.
    /// </param>
    /// <param name="entity">
    /// Entity on which the action will be executed.
    /// </param>
    /// <returns>
    /// The result generated by the operation, or a
    /// <see cref="ServiceResult"/> representing an error in it.
    /// </returns>
    protected ServiceResult? Perform<TModel>(CrudAction action, Func<TModel, EntityEntry<TModel>> operation, TModel entity) where TModel : Model
    {
        return TryCall(action, operation, [entity]);
    }

    /// <summary>
    /// Gets a <see cref="ServiceResult"/> that represents a failed
    /// <see cref="ServiceResult"/> from the produced exception.
    /// </summary>
    /// <param name="ex">Exception that occurred.</param>
    /// <returns>
    /// A result that represents and describes a failure in the
    /// requested operation.
    /// </returns>
    protected static ServiceResult ResultFromException(Exception ex)
    {
        return ex switch
        {
            null => throw new ArgumentNullException(nameof(ex)),
            NullReferenceException _ => NotFound,
            TaskCanceledException _ => NetworkFailure,
            DbUpdateConcurrencyException _ => ConcurrencyFailure,
            DbUpdateException _ => DbFailure,
            RetryLimitExceededException _ => NetworkFailure,
            _ => ex,
        };
    }

    /// <summary>
    /// Maps the <see cref="EntityState"/> value to its equivalent
    /// value of type <see cref="CrudAction"/>.
    /// </summary>
    /// <param name="state">
    /// Value to convert.
    /// </param>
    /// <returns>
    /// A <see cref="CrudAction"/> value equivalent to the
    /// specified <see cref="EntityState"/>.
    /// </returns>
    protected static CrudAction Map(EntityState state)
    {
        return state switch
        {
            EntityState.Deleted => CrudAction.Write,
            EntityState.Modified => CrudAction.Write,
            EntityState.Added => CrudAction.Write,
            _ => CrudAction.Read
        };
    }

    /// <inheritdoc/>
    protected override void OnDispose()
    {
        _context.Dispose();
    }

    /// <inheritdoc/>
    protected override async ValueTask OnDisposeAsync()
    {
        await _context.DisposeAsync();
    }

    private static T CreateContext(DbContextOptions? o)
    {
        try
        {
            return o is null
                ? typeof(T).New<T>()
                : typeof(T).New<T>(o);
        }
        catch (Exception ex)
        {
            throw new ClassNotInstantiableException(ex);
        }
    }

    private static ChangeTrackerItem? GetFromResult(CrudAction action, object? result)
    {
        return new ChangeTrackerItem(ChangeTrackerChangeType.NoChange, result switch
        {
            Model m => m,
            EntityEntry e => e.Entity as Model,
            IQueryable<Model> q when q.Count() == 1 => q.Single(),
            _ => null
        });
    }

    private protected CrudTransactionBase(IMiddlewareRunner runner, T contextInstance)
    {
        _runner = runner;
        _context = contextInstance;
    }
}