using TheXDS.Triton.Services;

namespace TheXDS.Triton.Component;

/// <summary>
/// Implements a middleware execution context info that receves a collection of
/// <see cref="ChangeTrackerItem"/> and passes through this data to the CRUD
/// operation to execute.
/// </summary>
/// <typeparam name="TResult">
/// Type of <see cref="ServiceResult"/> generated by the CRUD operation.
/// </typeparam>
/// <param name="action">Kind of CRUD action to be performed.</param>
/// <param name="changeTrackerItems">
/// Collection of <see cref="ChangeTrackerItem"/> elements to pass through to
/// the middleware execution context.
/// </param>
/// <param name="operation">
/// CRUD operation to execute, which receives the specified
/// <paramref name="changeTrackerItems"/>.
/// </param>
public class ChangeTrackerPassthroughExecutionContextInfo<TResult>(
    CrudAction action,
    IEnumerable<ChangeTrackerItem> changeTrackerItems,
    Func<IEnumerable<ChangeTrackerItem>, Task<TResult?>> operation)
    : IExecutionContextInfo<TResult> where TResult : notnull, ServiceResult, new()
{
    private readonly IEnumerable<ChangeTrackerItem> _changeTrackerItems = changeTrackerItems;

    /// <summary>
    /// Initializes a new instance of the <see cref="ChangeTrackerPassthroughExecutionContextInfo{TResult}"/>
    /// class, specifying a non-asyncronous method as the operation to be
    /// executed.
    /// </summary>
    /// <param name="action">Kind of CRUD action to be performed.</param>
    /// <param name="changeTrackerItems">
    /// Collection of <see cref="ChangeTrackerItem"/> elements to pass through to
    /// the middleware execution context.
    /// </param>
    /// <param name="operation">
    /// CRUD operation to execute, which receives the specified
    /// <paramref name="changeTrackerItems"/>.
    /// </param>
    public ChangeTrackerPassthroughExecutionContextInfo(
        CrudAction action,
        IEnumerable<ChangeTrackerItem> changeTrackerItems,
        Func<IEnumerable<ChangeTrackerItem>, TResult?> operation)
        : this(action, changeTrackerItems, e => Task.FromResult(operation.Invoke(e)))
    { }

    /// <inheritdoc/>
    public CrudAction Action { get; } = action;

    /// <inheritdoc/>
    public IEnumerable<ChangeTrackerItem>? PrologueData => _changeTrackerItems;

    /// <inheritdoc/>
    public Func<ServiceResult?, IEnumerable<ChangeTrackerItem>?>? EpilogueData => _ => _changeTrackerItems;

    /// <inheritdoc/>
    public Func<Task<TResult?>> Operation => () => operation.Invoke(_changeTrackerItems);
}
