using TheXDS.Triton.Services;

namespace TheXDS.Triton.Component;

/// <summary>
/// Defines a set of members to implement by a type that provides parameters to
/// a <see cref="MiddlewareExecutionContext"/>.
/// </summary>
/// <typeparam name="TResult">
/// Type of result returned by the underlying operation.
/// </typeparam>
public interface IExecutionContextInfo<TResult> where TResult : notnull, ServiceResult, new()
{
    /// <summary>
    /// Represents the CRUD action to perform. Determines the context for
    /// prologue and epilogue processing.
    /// </summary>
    CrudAction Action { get; }

    /// <summary>
    /// Gets or sets the collection of change tracker items representing the
    ///  prologue data.
    /// </summary>
    IEnumerable<ChangeTrackerItem>? PrologueData { get; }

    /// <summary>
    /// Gets or sets a delegate that generates a collection of change tracking
    ///  items based on the specified service
    /// result.
    /// </summary>
    /// <remarks>
    /// The delegate can be null if no epilogue data is required. When set, the
    /// function is invoked with the result of the service operation to produce
    /// additional change tracking information. The returned collection may be
    /// <see langword="null"/> if there are no changes to track.
    /// </remarks>
    Func<ServiceResult?, IEnumerable<ChangeTrackerItem>?>? EpilogueData { get; }

    /// <summary>
    /// Gets a reference to the operation to be executed.
    /// </summary>
    Func<Task<TResult?>> Operation { get; }

    /// <summary>
    /// Invokes the CRUD operation asyncronously.
    /// </summary>
    /// <returns>
    /// A <see cref="Task"/> that can be used to await the async operation,
    /// which returns the <typeparamref name="TResult"/> generated by the
    /// operation.
    /// </returns>
    Task<TResult?> InvokeOperationAsync() => Operation.Invoke();
}
