using TheXDS.Triton.Services;

namespace TheXDS.Triton.Component;

/// <summary>
/// Implements a simple execution context info that runs a CRUD action,
/// optionally allowing the user to manually specify the prologue and epilogue
/// data to pass over.
/// </summary>
/// <typeparam name="TResult">
/// Type of <see cref="ServiceResult"/> generated by the CRUD operation.
/// </typeparam>
/// <param name="action">Kind of CRUD action to be performed.</param>
/// <param name="operation">Operation to be executed.</param>
public class SimpleAsyncExecutionContextInfo<TResult>(CrudAction action, Func<Task<TResult?>> operation) : IExecutionContextInfo<TResult> where TResult : notnull, ServiceResult, new()
{
    /// <inheritdoc/>
    public CrudAction Action { get; set; } = action;

    /// <inheritdoc/>
    public IEnumerable<ChangeTrackerItem>? PrologueData { get; set; } = null;

    /// <inheritdoc/>
    public Func<ServiceResult?, IEnumerable<ChangeTrackerItem>?>? EpilogueData { get; set; } = null;

    /// <inheritdoc/>
    public Func<Task<TResult?>> Operation { get; } = operation;

    /// <summary>
    /// Initializes a new instance of the <see cref="SimpleAsyncExecutionContextInfo{TResult}"/>
    /// class, specifying a non-asyncronous method as the operation to be
    /// executed.
    /// </summary>
    /// <param name="action">Kind of CRUD action to be performed.</param>
    /// <param name="operation">Syncronous operation to be executed.</param>
    public SimpleAsyncExecutionContextInfo(CrudAction action, Func<TResult?> operation) : this(action, () => Task.FromResult(operation.Invoke()))
    {
    }
}
