<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\StringTables\*.deflate" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\StringTables\*.deflate" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TheXDS.MCART" Version="1.0.0-alpha.3" />
  </ItemGroup>
</Project>
